title: Title of your CV site
profile_img: /assets/img/profile.webp
icon_img: /assets/img/icon.webp

name: "Zhuotao Wang"
job: "〈Your Job Here〉"

phone_number: 202-674-0803
address: Washington, DC
email: zhuotao26@outlook.com
linkedin_username: www.linkedin.com/in/zhuotaowang


# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /resume
baseurl:

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
